/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClubsRouteImport } from './routes/clubs'
import { Route as GamesRouteImport } from './routes/games'
import { Route as KeeperRouteImport } from './routes/keeper'
import { Route as PlayersRouteImport } from './routes/players'
import { Route as RatingsRouteImport } from './routes/ratings'
import { Route as RecordRouteImport } from './routes/record'
import { Route as TableCardsRouteImport } from './routes/table-cards'
import { Route as PlayersPlayerIdRouteImport } from './routes/players_.$playerId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubsRoute = ClubsRouteImport.update({
  id: '/clubs',
  path: '/clubs',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const KeeperRoute = KeeperRouteImport.update({
  id: '/keeper',
  path: '/keeper',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersRoute = PlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => rootRouteImport,
} as any)
const RatingsRoute = RatingsRouteImport.update({
  id: '/ratings',
  path: '/ratings',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordRoute = RecordRouteImport.update({
  id: '/record',
  path: '/record',
  getParentRoute: () => rootRouteImport,
} as any)
const TableCardsRoute = TableCardsRouteImport.update({
  id: '/table-cards',
  path: '/table-cards',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersPlayerIdRoute = PlayersPlayerIdRouteImport.update({
  id: '/players_/$playerId',
  path: '/players/$playerId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clubs': typeof ClubsRoute
  '/games': typeof GamesRoute
  '/keeper': typeof KeeperRoute
  '/players': typeof PlayersRoute
  '/ratings': typeof RatingsRoute
  '/record': typeof RecordRoute
  '/table-cards': typeof TableCardsRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clubs': typeof ClubsRoute
  '/games': typeof GamesRoute
  '/keeper': typeof KeeperRoute
  '/players': typeof PlayersRoute
  '/ratings': typeof RatingsRoute
  '/record': typeof RecordRoute
  '/table-cards': typeof TableCardsRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clubs': typeof ClubsRoute
  '/games': typeof GamesRoute
  '/keeper': typeof KeeperRoute
  '/players': typeof PlayersRoute
  '/ratings': typeof RatingsRoute
  '/record': typeof RecordRoute
  '/table-cards': typeof TableCardsRoute
  '/players_/$playerId': typeof PlayersPlayerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clubs'
    | '/games'
    | '/keeper'
    | '/players'
    | '/ratings'
    | '/record'
    | '/table-cards'
    | '/players/$playerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clubs'
    | '/games'
    | '/keeper'
    | '/players'
    | '/ratings'
    | '/record'
    | '/table-cards'
    | '/players/$playerId'
  id:
    | '__root__'
    | '/'
    | '/clubs'
    | '/games'
    | '/keeper'
    | '/players'
    | '/ratings'
    | '/record'
    | '/table-cards'
    | '/players_/$playerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClubsRoute: typeof ClubsRoute
  GamesRoute: typeof GamesRoute
  KeeperRoute: typeof KeeperRoute
  PlayersRoute: typeof PlayersRoute
  RatingsRoute: typeof RatingsRoute
  RecordRoute: typeof RecordRoute
  TableCardsRoute: typeof TableCardsRoute
  PlayersPlayerIdRoute: typeof PlayersPlayerIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubs': {
      id: '/clubs'
      path: '/clubs'
      fullPath: '/clubs'
      preLoaderRoute: typeof ClubsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keeper': {
      id: '/keeper'
      path: '/keeper'
      fullPath: '/keeper'
      preLoaderRoute: typeof KeeperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players': {
      id: '/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof PlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ratings': {
      id: '/ratings'
      path: '/ratings'
      fullPath: '/ratings'
      preLoaderRoute: typeof RatingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/record': {
      id: '/record'
      path: '/record'
      fullPath: '/record'
      preLoaderRoute: typeof RecordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/table-cards': {
      id: '/table-cards'
      path: '/table-cards'
      fullPath: '/table-cards'
      preLoaderRoute: typeof TableCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players_/$playerId': {
      id: '/players_/$playerId'
      path: '/players/$playerId'
      fullPath: '/players/$playerId'
      preLoaderRoute: typeof PlayersPlayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClubsRoute: ClubsRoute,
  GamesRoute: GamesRoute,
  KeeperRoute: KeeperRoute,
  PlayersRoute: PlayersRoute,
  RatingsRoute: RatingsRoute,
  RecordRoute: RecordRoute,
  TableCardsRoute: TableCardsRoute,
  PlayersPlayerIdRoute: PlayersPlayerIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
